CREATE TABLE IF NOT EXISTS Metric (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    description TEXT,
    value DOUBLE PRECISION NOT NULL,
    timestamp BIGINT NOT NULL
    );